name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Check format
        run: cargo +nightly fmt --check

  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable

      - name: Check docs
        run: cargo doc --workspace --no-deps --document-private-items
        env:
          RUSTDOCFLAGS: -D warnings

  clippy:
    name: Clippy
    needs: [format, docs]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Run clippy
        run: cargo clippy --workspace
        env:
          RUSTFLAGS: -D warnings

  debian:
    name: Release DEB packages
    needs: clippy
    runs-on: ubuntu-22.04-arm
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: Install cargo-deb
        run: cargo install cargo-deb

      - name: Build argon-v2-fan DEB package
        run: cargo deb -p argon-v2-fan
        
      - name: Build argon-v3-fan DEB package
        run: cargo deb -p argon-v3-fan

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/debian/*.deb
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  home_assistant:
    runs-on: ubuntu-22.04-arm
    needs: clippy
    permissions:
      contents: write
    strategy:
      matrix:
        package: ["argon-v2-fan", "argon-v3-fan"]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      
      - name: Extract version
        run: |
          VERSION=`cargo pkgid -p ${{ matrix.package }} | awk -F'[#@]' '{print $NF}'`
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./home_assistant/Dockerfile
          push: true
          platforms: linux/arm64
          build-args: ARGON_FAN="${{ matrix.package }}"
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.package }}:${{ env.VERSION }}
            ghcr.io/${{ github.repository_owner }}/${{ matrix.package }}:latest